### ISSUE TITLE
Proposal: use OpenAPI to describe the routes

### ISSUE THREAD

**Issue by souenzzo** [avelino/moclojer#1]
This project currently use a custom YAML format to describe the routes.

It would be nice if it uses as a base for this YAML config file, the OpenAPI format.

Some possible benefits for this move:

- Developer familiarity: developers already know OpenAPI format
- Tooling: we can generate auto-docs from it.

Here how the [first example endpoint](https://github.com/avelino/moclojer/blob/e4a763c8c52efc195e5947654497a6ef7f07c0b2/moclojer.yml#L3-L16) can be represented.

```yaml
paths:
  /hello-world:
    get:
      ## Your new mockResponse attribute
      mockResponse:
        status: 200
        headers:
          Content-Type: application/json
        body: >
        {
          "hello": "Hello, World!"
        }
      ## Other OpenAPI v3 attributes, that may be used to check if the request is valid
      ## or just use to show an autodoc webpage.
      tags:
        - hello
        - world
      parameters:
        - name: username
          in: path
          description: Username of the user to send hello
          required: false
          schema:
            type: string
```

Pending tasks:
- [ ] Check if `mockResponse` is a name allowed to extension in openAPI spec

Future work:

- Allow situations where `openapi-spec.yaml` already exists, and we just want to add mock to this spec. In OpenAPI, each operation can have a unique `OperationID`. We can use it and provide an extra file, `operationId->mock.yaml`, allowing to generate mocks to a existing openapi spec.
