### ISSUE TITLE
JWT authentication

### ISSUE THREAD

**Issue by avelino** [avelino/moclojer#32]
Support for _"closed"_ endpoint by authentication

- validate http header if token is valid `Authorization: Bearer <token>`

**Comment by souenzzo** [comment]
OpenAPI has the concept of "Security" in paths/routes that we can flow

https://swagger.io/specification/

**Comment by avelino** [comment]
> OpenAPI has the concept of "Security" in paths/routes that we can flow

it is important that moclojer's own specification has a similar behavior to openapi's, this document will help a lot to define how we will do the implementation

**Comment by avelino** [comment]
moclojer spec for **http header** `Authorization`

```yaml
- auth
    token: ab123
    all_endpoint: false # default `false`, forces all endpoints to have authentication
    domain: moclojer.com # optional
- endpoint:
    auth: true # default `false`, if `auth.all_endpoint: true`, it is not necessary to activate this option
    auth_token: abc123 # optional, if `auth: true` it has priority over this attribute
    [...]
```
