### ISSUE TITLE
support for multiple domains in the specification (configuration)

### ISSUE THREAD

**Issue by avelino** [avelino/moclojer#47]
```yaml
- endpoint:
    host: moclojer.com
    method: GET
    path: /multihost
    response:
      status: 200
      headers:
        Content-Type: application/json
      body: >
        {
          "domain": "moclojer.com"
        }

- endpoint:
    host: sub.moclojer.com
    method: GET
    path: /multihost-sub
    response:
      status: 200
      headers:
        Content-Type: application/json
      body: >
        {
          "domain": "sub.moclojer.com"
        }
```
