### ISSUE TITLE
dynamic endpoint support

### ISSUE THREAD

**Issue by avelino** [avelino/moclojer#7]
**path:** `/hi/:username`

When receiving a parameter in the **URL** it must pass it to the template, being possible to use the parameter in the return `body`

**`yml` example:**
```yaml
- endpoint:
    method: GET
    path: /hi/:username
    response:
      status: 200
      headers:
        Content-Type: application/json
      body: >
        {
          "username": "{{username}}"
        }
```

## recommendation
For template rendering we can use [Selmer](https://github.com/yogthos/Selmer), it keeps up to date and has a friendly syntax.

**Example of use:**
```clj
(parser/render "{{username}}" {:username "moclojer"})
```
